sudo: false
language: java
jdk:
- oraclejdk7
notifications:
  email:
    recipients:
    - dev@tecsinapse.com.br
    on_success: change
    on_failure: always
after_success:
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d
- bash .travis_after_success.sh
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - GPG_DIR="`pwd`/travis"
  - secure: a4ATLBkk/LGy7yHKQehHeQMws2DQ4kpC35fvZtANsJE/nCUxxrzLg+XMZ7vsGVipvZc7eB2Izz4bkK8SP2B4jJsFtlmYWrFbgw7Hr3ESz2Gsx1Q/kNc7DXbd8Nus6T70LuyH0R756dD6Lkh1ggXxQkYH9iOj4gSk+xtY+sDusEGIpEDVi3FTvKnoDHjt+0O8e21WLJOElNOxp63W3FnszoKZItxtpUSIYfrHAJ8QCmqAK7gEPfDfKvD4bkwXDG33AFtlFjE63tALHga+xcKB2is4EO2TON8A9x0smovcQldnzHAMcNLyFm31AWws6sy4To44Ima2UFv+DsByfG1boAG5weGZnFwCgSrFrl0ZmcHgom6u98IK40ZE1qz62sE6J7YAVOfkSkxtoA9O9joxLj2P1WCSTlsTerAcSWcDK1a8RMK+PiSTwP2O43rH/FSuu5nXbQTuzcAjX6s+x5V4speYTnnQQTWjZiy3qcWwkvHmsIhVsaM7h6CWLG2MGCO5HSVBClZmQteIFc10Zg+TEko//z0n2HqS/i2W6wDfpg2clpgsAcdqV0KIuob2VdyUAzR1SHIIuce/aRDXB7oLWMoKXXm9hvQOZLE/f508wfVK2trP0P16lnMoOZTFc86rNKZ8yv1J2evlUDaRkKBT4C/i5kTQUqlL+PgossAdqv8=
  - secure: RACJrQSKcqJUaIVbIHB0OgkY5bXwWxWkX86AOJugjwqPtO9ELQBJPfRTPSLo4vmClXn9H7WBEELQUYveGPnRXvI3X1xlUPY1RXzTFq1eBKGMkjtWRB3gAG1sMpuiOkxsKGITcUF//M8zQxVMFqjIzVEESwWa8mWCLKt/OiBXHIBrzZIH2Fx8P5WQXdmP5Libfpwvnn5Gc+3+DkJDRzf6GUbG93gIutL7UDyV55WBpBdKtMng+iZrqBGf0+ZVS6N2Nla+ueUL+if75pqZBTdeJR8CmOKV2DCASemycZPTWqqb6tTv8lh0J/tiYtc0wP84PyjGT8tdXaMR5Jh5qjZiy+23KymFeNO4MYL3Mjm+n7T+9QKUXAVD0eJSk+5P6cXtlvaJvoWH3qRuZJHnNqix4hwmrHcJtU5Naq32/qXDqHyHjfxrLm9L1+/mBx474tiaEqo+ul9SQb0MhFFAy2YSZul35oaGd4MRM8ujVxIX6h7dV+YTehoOfHCEvTQGkL+x260AquN7tM46OH1m4CU2NIS9M61UcwNnqLCHYoDUlPGnZhKmtG4LaozbF36XSy3eRmB7C+3seHAUwzDJyn04uW0mtIp2pSiqnycOobGQGHwzv1vEoqwx/thBy8ricnwHBHF+p2k5jFrS+blS4OAHoNtf0UEV28ghVgaqN1FjciA=
  - secure: cp3RnfeqWseaqwJLp25f9RBeiZICylRkblR+icWgX/8Y4C75GDdioBtgCSswaKOAMzz4JpTfzV9KErKjgllNIBlWxMaAqlvr4E3dkQLpHv/5fz3mV/VdLRnZ6Biwi7XQ2G4QxZ7M7CNwblXXeUk7uEmTJsoxyV2ttWC8XSWFUIY7klQCOCPdoOuRD1R7Vh+U6wDX/8cslb/dY+HMTRxAFvw0/wFIrprBWjEdEpYcKnsnHAq4w2Tpi5TT5UVELtQWxXyywcwI9nnCTfDyqtvmTGPC5DitSDqY0CdtbRBt+o7oUNLWZhVNbrDtJhOt1pzqn7LYTCDdoe+VXXFdK75ap3uC0xRfCYBvnwN4GNhGkBlTV08AetRvbKKL/Z0dykt/PcVMOylnS6GGqfn03PXcMXzc5qinaRBrRFvQrtcf70FDS9vO3EAKzZyK8gCMEBv+VhHJ6g9VcuP05BF0U5Tq2qKKyJ9Dvk6faKAHNYI6aaP5eCQbEaMEpZiZ+mfrLQR4Zoj+D/jHYdiaW5CW6tiIjEVaee44rZFpHZ1/rkRFY9WMUoYcANj67ENi/20JdG1NQciK23/Yr75fuGYT9SDem3mFhGtap5AjGoKkrUnxUnvU/3q6/zmGa/gXkqQNCnFN80qD32FROwdF4omjpdOFvQBafccEL6tR2LRmmO6qNjg=
